name : Deploy en VPS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        #Define entorno, y clona el repo del VPS volatil
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Install sshpass
              run: sudo apt-get install sshpass -y

            - name: Create .ssh directory
              run: mkdir -p ~/.ssh
        
            - name: Add remote host to known_hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Execute command on VPS
              env: 
                SSHPASS: ${{ secrets.SSH_PASSWORD }}
              run: sshpass -e ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pm2 stop basico && cd server-bruteforve && git pull && npm install && pm2 start basico &"